version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postcomment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  api:
    build:
      context: server
    command: sh -c "yarn typeorm migration:run && yarn dev"
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "3333:3333"
    depends_on:
      - db
  web:
    build: 
      context: web
    volumes: 
      - ./web/:/usr/src/web
    ports: 
      - "80:80"
    depends_on: 
      - api